name: Build and Deploy
on:
  push:
    branches:
      - secret
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: All things angular
      uses: pierbotteroweb/angular-aws-secrets@cadc51fd9f25e0bcb6134f8a3d3553f23ea471f9 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: /angular-aws-secrets/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: secret # The branch the action should deploy to.
        angular_dist_build_folder: dist/angular-aws-secrets # The folder where your project is supposed to be after running ng build by the action.

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch